/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pdg_opencvexam_MainActivity */

#ifndef _Included_com_example_pdg_opencvexam_MainActivity
#define _Included_com_example_pdg_opencvexam_MainActivity
#ifdef __cplusplus


#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>

using namespace cv;

extern "C" {
#endif
/*
 * Class:     com_example_pdg_opencvexam_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_pdg_opencvexam_MainActivity_ConvertRGBtoGray
  (JNIEnv *env, jobject instance, jlong matAddrInput, jlong matAddrResult){

        Mat &matInput = *(Mat *)matAddrInput;
        Mat &matResult = *(Mat *)matAddrResult;

        cvtColor(matInput, matResult, CV_RGBA2GRAY);
   }
   }

#ifdef __cplusplus

#endif
#endif
